version: 2

before:
  hooks:
    - go mod tidy


builds:
  - id: linux_amd64
    goos: [linux]
    goarch: [amd64]
    ldflags: "-s -w"
    binary: bx

  - id: linux_arm64
    goos: [linux]
    goarch: [arm64]
    ldflags: "-s -w"
    binary: bx

  - id: windows_amd64
    goos: [windows]
    goarch: [amd64]
    ldflags: "-s -w"
    binary: bx

  - id: windows_arm64
    goos: [windows]
    goarch: [arm64]
    ldflags: "-s -w"
    binary: bx

  - id: darwin_amd64
    goos: [darwin]
    goarch: [amd64]
    ldflags: "-s -w"
    binary: bx

  - id: darwin_arm64
    goos: [darwin]
    goarch: [arm64]
    ldflags: "-s -w"
    binary: bx


archives:
  - id: linux_amd64
    builds: [linux_amd64]
    formats: ['tar.gz']
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

  - id: linux_arm64
    builds: [linux_arm64]
    formats: ['tar.gz']
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

  - id: windows_amd64
    builds: [windows_amd64]
    formats: ['tar.gz']
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

  - id: windows_arm64
    builds: [windows_arm64]
    formats: ['tar.gz']
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

  - id: darwin_amd64
    builds: [darwin_amd64]
    formats: ['tar.gz']
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

  - id: darwin_arm64
    builds: [darwin_arm64]
    formats: ['tar.gz']
    name_template: "{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  ids:
    - linux_amd64
    - linux_arm64
    - windows_amd64
    - windows_arm64
    - darwin_amd64
    - darwin_arm64
