name: Lint Go Code

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.1.6/golangci-lint-2.1.6-linux-amd64.tar.gz | tar -xzv -C /tmp
          mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin/

      - name: Run golangci-lint
        run: golangci-lint run --timeout 5m

      - name: Run gofmt
        run: |
            gofmt -s -w .
            git diff --exit-code

      - name: Gosec Security Checker
        uses: securego/gosec@v2.22.4
