name: Lint Go Code

permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639
        with:
          go-version: '1.24'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.1.6/golangci-lint-2.1.6-linux-amd64.tar.gz | tar -xzv -C /tmp
          mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin/

      - name: Run golangci-lint
        run: golangci-lint run --timeout 5m

      - name: Run gofmt
        run: |
            gofmt -s -w .
            git diff --exit-code
