name: Go

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Set up Go
        uses: actions/setup-go@34829cb9acb0c3aab260216f67d0867cc080dca5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
