name: Security Scanner

permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  gosec:
    name: Gosec Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Set up Go
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639
        with:
          go-version: '1.25'

      - name: Run gosec
        uses: securego/gosec@cee0aeae8a8b6c2d59571e500bc69010f2630db6
        with:
          args: ./...
