name: Security Scanner

permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  gosec:
    name: Gosec Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - name: Set up Go
        uses: actions/setup-go@34829cb9acb0c3aab260216f67d0867cc080dca5
        with:
          go-version-file: go.mod

      - name: Run gosec
        uses: securego/gosec@cee0aeae8a8b6c2d59571e500bc69010f2630db6
        with:
          args: ./...
