name: Run tests and upload coverage

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@34829cb9acb0c3aab260216f67d0867cc080dca5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pixel365/bx
